In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline
import seaborn as sns
# Importing the required packages 
import pandas as pd 
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

In [2]:
KDDTest = pd.read_csv('KDDTest+.csv')
KDDTrain = pd.read_csv('KDDTrain+.csv')


In [3]:
mapping = {'ipsweep': 'Probe','satan': 'Probe','nmap': 'Probe','portsweep': 'Probe','saint': 'Probe','mscan': 'Probe',
        'teardrop': 'DoS','pod': 'DoS','land': 'DoS','back': 'DoS','neptune': 'DoS','smurf': 'DoS','mailbomb': 'DoS',
        'udpstorm': 'DoS','apache2': 'DoS','processtable': 'DoS',
        'perl': 'U2R','loadmodule': 'U2R','rootkit': 'U2R','buffer_overflow': 'U2R','xterm': 'U2R','ps': 'U2R',
        'sqlattack': 'U2R','httptunnel': 'U2R',
        'ftp_write': 'R2L','phf': 'R2L','guess_passwd': 'R2L','warezmaster': 'R2L','warezclient': 'R2L','imap': 'R2L',
        'spy': 'R2L','multihop': 'R2L','named': 'R2L','snmpguess': 'R2L','worm': 'R2L','snmpgetattack': 'R2L',
        'xsnoop': 'R2L','xlock': 'R2L','sendmail': 'R2L',
        'normal': 'Normal'
        }

In [4]:
# Apply attack class mappings to the dataset
KDDTrain['attack_class'] = KDDTrain['labels'].apply(lambda v: mapping[v])
KDDTest['attack_class'] = KDDTest['labels'].apply(lambda v: mapping[v])

In [5]:
from sklearn.preprocessing import LabelEncoder
le_protocol = LabelEncoder()
le_service = LabelEncoder()
le_flag = LabelEncoder()
KDDTrain['protocol_type'] = le_protocol.fit_transform(KDDTrain.protocol_type)
KDDTrain['service'] = le_protocol.fit_transform(KDDTrain.service)
KDDTrain['flag'] = le_protocol.fit_transform(KDDTrain.flag)
KDDTrain
KDDTest['protocol_type'] = le_protocol.fit_transform(KDDTest.protocol_type)
KDDTest['service'] = le_protocol.fit_transform(KDDTest.service)
KDDTest['flag'] = le_protocol.fit_transform(KDDTest.flag)

In [6]:
X_train = KDDTrain.iloc[:,0:40]  # All rows, omit last  2 column
y_train = KDDTrain.iloc[:,42]# All rows, only the last column

X_test = KDDTest.iloc[:,0:40]  # All rows, omit last 2 column
y_test = KDDTest.iloc[:,42]# All rows, only the last column

#  Predicting class attack

### KNN

In [7]:
from sklearn.neighbors import KNeighborsClassifier
knn_model = KNeighborsClassifier()
knn_model.fit(X_train,y_train)
knn_prediction = knn_model.predict(X_test)

In [8]:
print("Accuracy score for KNN:",accuracy_score(y_test,knn_prediction))

Accuracy score for KNN: 0.7274219304471257


#### Predicting the actual labels

In [9]:
X_train = KDDTrain.iloc[:,0:40]  # All rows, omit last 2 columns
y_train = KDDTrain.iloc[:,41]# All rows, only the second last column

X_test = KDDTest.iloc[:,0:40]  # All rows, omit last 2 column
y_test = KDDTest.iloc[:,41]# All rows, only the second last  column

### Predicting the actual labels

In [10]:
knn_model = KNeighborsClassifier()
knn_model.fit(X_train,y_train)
knn_prediction = knn_model.predict(X_test)

In [11]:
print("Accuracy score for KNN:",accuracy_score(y_test,knn_prediction))

Accuracy score for KNN: 0.705376153300213


#### SVM

In [12]:
X_train = KDDTrain.iloc[:,0:40]  # All rows, omit last  2 column
y_train = KDDTrain.iloc[:,42]# All rows, only the last column

X_test = KDDTest.iloc[:,0:40]  # All rows, omit last 2 column
y_test = KDDTest.iloc[:,42]# All rows, only the last column

#  Predicting class attack

In [13]:

from sklearn.svm import SVC

plf=SVC(random_state=0)

In [14]:
    plf.fit(X_train, y_train)

SVC(random_state=0)

In [15]:
y_pred = plf.predict(X_test)

In [16]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(y_test,y_pred))  
print(classification_report(y_test,y_pred))  
print(accuracy_score(y_test, y_pred))

[[   0 7458    0    0    0]
 [   0 9709    0    2    0]
 [   0 2421    0    0    0]
 [   0 2752    2    0    0]
 [   0  200    0    0    0]]


C:\Users\ninadgorey\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


              precision    recall  f1-score   support

         DoS       0.00      0.00      0.00      7458
      Normal       0.43      1.00      0.60      9711
       Probe       0.00      0.00      0.00      2421
         R2L       0.00      0.00      0.00      2754
         U2R       0.00      0.00      0.00       200

    accuracy                           0.43     22544
   macro avg       0.09      0.20      0.12     22544
weighted avg       0.19      0.43      0.26     22544

0.43066891412349184


In [17]:
print(accuracy_score(y_test, y_pred))

0.43066891412349184


### Logistic Regression

In [18]:
from sklearn import preprocessing
# Preprocess
enc = preprocessing.OrdinalEncoder()

encoded_dataset = enc.fit_transform(KDDTrain)  # All categorical features are now numerical
X_train = encoded_dataset[:, :-2]  # All rows, omit last column
y_train = np.ravel(encoded_dataset[:, -1:])  # All rows, only the last column

In [19]:
# Repeat preprocessing for test data
encoded_dataset = enc.fit_transform(KDDTest)
X_test = encoded_dataset[:, :-2]
y_test = np.ravel(encoded_dataset[:, -1:])


In [20]:
from sklearn.linear_model import LogisticRegression

In [21]:
clf=LogisticRegression(random_state=0)

clf.fit(X_train, y_train)

C:\Users\ninadgorey\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(random_state=0)

In [22]:
y_pred = clf.predict(X_test)

In [23]:
print(accuracy_score(y_test, y_pred))

0.7301277501774308


In [24]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test,y_pred))  
print(classification_report(y_test,y_pred))  
print(accuracy_score(y_test, y_pred))

[[5498 1936   15    9    0]
 [ 443 8999  262    7    0]
 [ 190  290 1941    0    0]
 [   6 2537  189   22    0]
 [   4  127   65    4    0]]
              precision    recall  f1-score   support

         0.0       0.90      0.74      0.81      7458
         1.0       0.65      0.93      0.76      9711
         2.0       0.79      0.80      0.79      2421
         3.0       0.52      0.01      0.02      2754
         4.0       0.00      0.00      0.00       200

    accuracy                           0.73     22544
   macro avg       0.57      0.49      0.48     22544
weighted avg       0.72      0.73      0.68     22544

0.7301277501774308


C:\Users\ninadgorey\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [25]:
print(accuracy_score(y_test, y_pred))

0.7301277501774308
