In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline
import seaborn as sns
# Importing the required packages 
import pandas as pd 
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report
from sklearn.model_selection import RandomizedSearchCV

In [2]:
KDDTest = pd.read_csv('KDDTest+.csv')
KDDTrain = pd.read_csv('KDDTrain+.csv')


In [3]:
mapping = {'ipsweep': 'Probe','satan': 'Probe','nmap': 'Probe','portsweep': 'Probe','saint': 'Probe','mscan': 'Probe',
        'teardrop': 'DoS','pod': 'DoS','land': 'DoS','back': 'DoS','neptune': 'DoS','smurf': 'DoS','mailbomb': 'DoS',
        'udpstorm': 'DoS','apache2': 'DoS','processtable': 'DoS',
        'perl': 'U2R','loadmodule': 'U2R','rootkit': 'U2R','buffer_overflow': 'U2R','xterm': 'U2R','ps': 'U2R',
        'sqlattack': 'U2R','httptunnel': 'U2R',
        'ftp_write': 'R2L','phf': 'R2L','guess_passwd': 'R2L','warezmaster': 'R2L','warezclient': 'R2L','imap': 'R2L',
        'spy': 'R2L','multihop': 'R2L','named': 'R2L','snmpguess': 'R2L','worm': 'R2L','snmpgetattack': 'R2L',
        'xsnoop': 'R2L','xlock': 'R2L','sendmail': 'R2L',
        'normal': 'Normal'
        }

In [4]:
# Apply attack class mappings to the dataset
KDDTrain['attack_class'] = KDDTrain['labels'].apply(lambda v: mapping[v])
KDDTest['attack_class'] = KDDTest['labels'].apply(lambda v: mapping[v])

In [5]:
KDDTrain

duration protocol_type   service flag  src_bytes  dst_bytes  land  \
0              0           tcp  ftp_data   SF        491          0     0   
1              0           udp     other   SF        146          0     0   
2              0           tcp   private   S0          0          0     0   
3              0           tcp      http   SF        232       8153     0   
4              0           tcp      http   SF        199        420     0   
...          ...           ...       ...  ...        ...        ...   ...   
125968         0           tcp   private   S0          0          0     0   
125969         8           udp   private   SF        105        145     0   
125970         0           tcp      smtp   SF       2231        384     0   
125971         0           tcp    klogin   S0          0          0     0   
125972         0           tcp  ftp_data   SF        151          0     0   

        wrong_fragment  urgent  hot  ...  dst_host_same_srv_rate  \
0                    0       0    0  ...                    0.17   
1                    0       0    0  ...                    0.00   
2                    0       0    0  ...                    0.10   
3                    0       0    0  ...                    1.00   
4                    0       0    0  ...                    1.00   
...                ...     ...  ...  ...                     ...   
125968               0       0    0  ...                    0.10   
125969               0       0    0  ...                    0.96   
125970               0       0    0  ...                    0.12   
125971               0       0    0  ...                    0.03   
125972               0       0    0  ...                    0.30   

        dst_host_diff_srv_rate  dst_host_same_src_port_rate  \
0                         0.03                         0.17   
1                         0.60                         0.88   
2                         0.05                         0.00   
3                         0.00                         0.03   
4                         0.00                         0.00   
...                        ...                          ...   
125968                    0.06                         0.00   
125969                    0.01                         0.01   
125970                    0.06                         0.00   
125971                    0.05                         0.00   
125972                    0.03                         0.30   

        dst_host_srv_diff_host_rate  dst_host_serror_rate  \
0                              0.00                  0.00   
1                              0.00                  0.00   
2                              0.00                  1.00   
3                              0.04                  0.03   
4                              0.00                  0.00   
...                             ...                   ...   
125968                         0.00                  1.00   
125969                         0.00                  0.00   
125970                         0.00                  0.72   
125971                         0.00                  1.00   
125972                         0.00                  0.00   

        dst_host_srv_serror_rate  dst_host_rerror_rate  \
0                           0.00                  0.05   
1                           0.00                  0.00   
2                           1.00                  0.00   
3                           0.01                  0.00   
4                           0.00                  0.00   
...                          ...                   ...   
125968                      1.00                  0.00   
125969                      0.00                  0.00   
125970                      0.00                  0.01   
125971                      1.00                  0.00   
125972                      0.00                  0.00   

        dst_host_srv_rerror_rate   labels  attack_class  
0                    

## Random Forest 

In [6]:
from sklearn import preprocessing
from scipy.io.arff import loadarff
from sklearn.ensemble import RandomForestClassifier
import numpy as np

In [7]:
# Preprocess
enc = preprocessing.OrdinalEncoder()

encoded_dataset = enc.fit_transform(KDDTrain)  # All categorical features are now numerical
X_train = encoded_dataset[:, :-2]  # All rows, omit last column
y_train = np.ravel(encoded_dataset[:, -1:])  # All rows, only the last column

In [8]:
# Repeat preprocessing for test data
encoded_dataset = enc.fit_transform(KDDTest)
X_test = encoded_dataset[:, :-2]
y_test = np.ravel(encoded_dataset[:, -1:])


In [9]:
# rfc = RandomForestClassifier(random_state=10)
# params = {'bootstrap': ['True', 'False'], 'max_depth': [1,2,3], 'n_estimators': [10, 50, 100, 200, 500], 'max_features': [1,2,3,4,5,6,7,8]}
# rfc_grid = GridSearchCV(rfc, params, verbose = 1)
# rfc_grid_model = rfc_grid.fit(X_train, y_train)
# print(rfc_grid_model.best_estimator_)
# print(rfc_grid_model.best_score_)
# print("Best Parameter Set")
# print(rfc_grid_model.best_params_)

In [10]:
# Fit to model and predict
rfc = RandomForestClassifier()
y_pred = rfc.fit(X_train, y_train).predict(X_test)

In [11]:
total_datapoints = X_test.shape[0]
mislabeled_datapoints = (y_test != y_pred).sum()
correct_datapoints = total_datapoints-mislabeled_datapoints
percent_correct = (correct_datapoints / total_datapoints) * 100

print("RandomForestClassifier results for NSL-KDD:\n")
print("Total datapoints: %d\nCorrect datapoints: %d\nMislabeled datapoints: %d\nPercent correct: %.2f%%"
      % (total_datapoints, correct_datapoints, mislabeled_datapoints, percent_correct))

RandomForestClassifier results for NSL-KDD:

Total datapoints: 22544
Correct datapoints: 16448
Mislabeled datapoints: 6096
Percent correct: 72.96%


In [12]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(y_test,y_pred))  
print(classification_report(y_test,y_pred))  
print(accuracy_score(y_test, y_pred))

[[5401 1998   59    0    0]
 [  37 9473  201    0    0]
 [ 166  708 1547    0    0]
 [   0 2727    3   23    1]
 [   0  189    7    0    4]]
              precision    recall  f1-score   support

         0.0       0.96      0.72      0.83      7458
         1.0       0.63      0.98      0.76      9711
         2.0       0.85      0.64      0.73      2421
         3.0       1.00      0.01      0.02      2754
         4.0       0.80      0.02      0.04       200

    accuracy                           0.73     22544
   macro avg       0.85      0.47      0.48     22544
weighted avg       0.81      0.73      0.68     22544

0.7295954577714692


In [13]:
KDDTrain['attack_class'].unique()

array(['Normal', 'DoS', 'R2L', 'Probe', 'U2R'], dtype=object)

####  Label Encoding

In [14]:
KDDTrain

duration protocol_type   service flag  src_bytes  dst_bytes  land  \
0              0           tcp  ftp_data   SF        491          0     0   
1              0           udp     other   SF        146          0     0   
2              0           tcp   private   S0          0          0     0   
3              0           tcp      http   SF        232       8153     0   
4              0           tcp      http   SF        199        420     0   
...          ...           ...       ...  ...        ...        ...   ...   
125968         0           tcp   private   S0          0          0     0   
125969         8           udp   private   SF        105        145     0   
125970         0           tcp      smtp   SF       2231        384     0   
125971         0           tcp    klogin   S0          0          0     0   
125972         0           tcp  ftp_data   SF        151          0     0   

        wrong_fragment  urgent  hot  ...  dst_host_same_srv_rate  \
0                    0       0    0  ...                    0.17   
1                    0       0    0  ...                    0.00   
2                    0       0    0  ...                    0.10   
3                    0       0    0  ...                    1.00   
4                    0       0    0  ...                    1.00   
...                ...     ...  ...  ...                     ...   
125968               0       0    0  ...                    0.10   
125969               0       0    0  ...                    0.96   
125970               0       0    0  ...                    0.12   
125971               0       0    0  ...                    0.03   
125972               0       0    0  ...                    0.30   

        dst_host_diff_srv_rate  dst_host_same_src_port_rate  \
0                         0.03                         0.17   
1                         0.60                         0.88   
2                         0.05                         0.00   
3                         0.00                         0.03   
4                         0.00                         0.00   
...                        ...                          ...   
125968                    0.06                         0.00   
125969                    0.01                         0.01   
125970                    0.06                         0.00   
125971                    0.05                         0.00   
125972                    0.03                         0.30   

        dst_host_srv_diff_host_rate  dst_host_serror_rate  \
0                              0.00                  0.00   
1                              0.00                  0.00   
2                              0.00                  1.00   
3                              0.04                  0.03   
4                              0.00                  0.00   
...                             ...                   ...   
125968                         0.00                  1.00   
125969                         0.00                  0.00   
125970                         0.00                  0.72   
125971                         0.00                  1.00   
125972                         0.00                  0.00   

        dst_host_srv_serror_rate  dst_host_rerror_rate  \
0                           0.00                  0.05   
1                           0.00                  0.00   
2                           1.00                  0.00   
3                           0.01                  0.00   
4                           0.00                  0.00   
...                          ...                   ...   
125968                      1.00                  0.00   
125969                      0.00                  0.00   
125970                      0.00                  0.01   
125971                      1.00                  0.00   
125972                      0.00                  0.00   

        dst_host_srv_rerror_rate   labels  attack_class  
0                    

In [15]:
from sklearn.preprocessing import LabelEncoder
le_protocol = LabelEncoder()
le_service = LabelEncoder()
le_flag = LabelEncoder()
KDDTrain['protocol_type'] = le_protocol.fit_transform(KDDTrain.protocol_type)
KDDTrain['service'] = le_protocol.fit_transform(KDDTrain.service)
KDDTrain['flag'] = le_protocol.fit_transform(KDDTrain.flag)
KDDTrain
KDDTest['protocol_type'] = le_protocol.fit_transform(KDDTest.protocol_type)
KDDTest['service'] = le_protocol.fit_transform(KDDTest.service)
KDDTest['flag'] = le_protocol.fit_transform(KDDTest.flag)


#### Predicting labels

In [16]:
X_train = KDDTrain.iloc[:,0:40]  # All rows, omit last 2 columns
y_train = KDDTrain.iloc[:,41]# All rows, only the second last column

X_test = KDDTest.iloc[:,0:40]  # All rows, omit last 2 column
y_test = KDDTest.iloc[:,41]# All rows, only the second last  column

In [17]:
from xgboost import XGBClassifier
model = XGBClassifier(silent=0,
                     scale_pos_weight=1,
                     learning_rate=0.01,
                     colsample_bytree=0.6,
                     subsample=0.8,
                     objective='binary:logistic',
                     n_estimators=100,
                     reg_alpha=0.3,
                     max_depth=3,
                     gamma=1)

model.fit(X_train,y_train,verbose=True)


[19:08:29] WARNING: C:\Users\Administrator\workspace\xgboost-win64_release_1.2.0\src\learner.cc:516: 
Parameters: { scale_pos_weight, silent } might not be used.

  This may not be accurate due to some parameters are only used in language bindings but
  passed down to XGBoost core.  Or some parameters are not used but slip through this
  verification. Please open an issue if you find above cases.




XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=0.6, gamma=1, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.01, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=100, n_jobs=0, num_parallel_tree=1,
              objective='multi:softprob', random_state=0, reg_alpha=0.3,
              reg_lambda=1, scale_pos_weight=1, silent=0, subsample=0.8,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [18]:
preds = model.predict(X_test)

print(accuracy_score(y_test,preds))

0.7210787792760823


In [19]:
import xgboost as xgb
boost = xgb.XGBClassifier(max_depth=9,
                          subsample=0.9,
                          objective='multi:softmax',
                          num_class = 3,
                          min_child_weight=2,
                          colsample_bytree=0.7,
                          n_estimators=1000,
                          learning_rate=0.08,
                          n_jobs = -1)
boost.fit(X_train,y_train)
boost_pred = boost.predict(X_test)
accuracy_score(y_test,boost_pred)

0.7219659332860184

In [20]:


print(confusion_matrix(y_test,boost_pred))  
print(classification_report(y_test,boost_pred))  
print(accuracy_score(y_test, boost_pred))

[[  0 161   0 ...   0   0   0]
 [  0 346   0 ...   0   0   0]
 [  0   0   2 ...   0   0   0]
 ...
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   1 ...   0   0   0]]


C:\Users\ninadgorey\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ninadgorey\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


                 precision    recall  f1-score   support

        apache2       0.00      0.00      0.00       737
           back       0.68      0.96      0.80       359
buffer_overflow       0.67      0.10      0.17        20
      ftp_write       0.00      0.00      0.00         3
   guess_passwd       0.00      0.00      0.00      1231
     httptunnel       0.00      0.00      0.00       133
           imap       0.00      0.00      0.00         1
        ipsweep       0.73      0.99      0.84       141
           land       1.00      0.57      0.73         7
     loadmodule       0.00      0.00      0.00         2
       mailbomb       0.00      0.00      0.00       293
          mscan       0.00      0.00      0.00       996
       multihop       0.00      0.00      0.00        18
          named       0.00      0.00      0.00        17
        neptune       0.94      1.00      0.97      4657
           nmap       0.61      1.00      0.76        73
         normal       0.66    

### Predicting Class attack

In [21]:
X_train = KDDTrain.iloc[:,0:40]  # All rows, omit last  2 column
y_train = KDDTrain.iloc[:,42]# All rows, only the last column

X_test = KDDTest.iloc[:,0:40]  # All rows, omit last 2 column
y_test = KDDTest.iloc[:,42]# All rows, only the last column

In [22]:
from xgboost import XGBClassifier
model = XGBClassifier(silent=0,
                     scale_pos_weight=1,
                     learning_rate=0.01,
                     colsample_bytree=0.6,
                     subsample=0.8,
                     objective='binary:logistic',
                     n_estimators=100,
                     reg_alpha=0.3,
                     max_depth=3,
                     gamma=1)

model.fit(X_train,y_train,verbose=True)


[19:34:27] WARNING: C:\Users\Administrator\workspace\xgboost-win64_release_1.2.0\src\learner.cc:516: 
Parameters: { scale_pos_weight, silent } might not be used.

  This may not be accurate due to some parameters are only used in language bindings but
  passed down to XGBoost core.  Or some parameters are not used but slip through this
  verification. Please open an issue if you find above cases.




XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=0.6, gamma=1, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.01, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=100, n_jobs=0, num_parallel_tree=1,
              objective='multi:softprob', random_state=0, reg_alpha=0.3,
              reg_lambda=1, scale_pos_weight=1, silent=0, subsample=0.8,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [23]:
preds = model.predict(X_test)

print(accuracy_score(y_test,preds))

0.7139815471965933


In [24]:
import xgboost as xgb
boost = xgb.XGBClassifier(max_depth=9,
                          subsample=0.9,
                          objective='multi:softmax',
                          num_class = 3,
                          min_child_weight=2,
                          colsample_bytree=0.7,
                          n_estimators=1000,
                          learning_rate=0.08,
                          n_jobs = -1)
boost.fit(X_train,y_train)
boost_pred = boost.predict(X_test)

In [25]:
accuracy_score(y_test,boost_pred)

0.7729329311568488

In [26]:


print(confusion_matrix(y_test,boost_pred))  
print(classification_report(y_test,boost_pred))  
print(accuracy_score(y_test, boost_pred))

[[6192 1100  166    0    0]
 [  81 9419  210    0    1]
 [ 164  576 1681    0    0]
 [   0 2622    1  130    1]
 [   0  183   12    2    3]]
              precision    recall  f1-score   support

         DoS       0.96      0.83      0.89      7458
      Normal       0.68      0.97      0.80      9711
       Probe       0.81      0.69      0.75      2421
         R2L       0.98      0.05      0.09      2754
         U2R       0.60      0.01      0.03       200

    accuracy                           0.77     22544
   macro avg       0.81      0.51      0.51     22544
weighted avg       0.82      0.77      0.73     22544

0.7729329311568488
